/**
 * GratisBrockiBackend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: @springdoc.version@
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Message } from './message';
import { Picture } from './picture';
import { User } from './user';

export interface Item { 
    id?: number;
    createdDate?: Date;
    lastModifiedDate?: Date;
    archivedDate?: Date;
    title?: string;
    description?: string;
    zipCode?: number;
    category?: Item.CategoryEnum;
    condition?: Item.ConditionEnum;
    owner?: User;
    pictures?: Array<Picture>;
    messages?: Array<Message>;
}
export namespace Item {
    export type CategoryEnum = 'ChildrenItemCategory' | 'ClothingItemCategory' | 'GardenItemCategory' | 'HouseholdItemCategory' | 'SportItemCategory' | 'VehicleItemCategory' | 'OtherItemCategory';
    export const CategoryEnum = {
        ChildrenItemCategory: 'ChildrenItemCategory' as CategoryEnum,
        ClothingItemCategory: 'ClothingItemCategory' as CategoryEnum,
        GardenItemCategory: 'GardenItemCategory' as CategoryEnum,
        HouseholdItemCategory: 'HouseholdItemCategory' as CategoryEnum,
        SportItemCategory: 'SportItemCategory' as CategoryEnum,
        VehicleItemCategory: 'VehicleItemCategory' as CategoryEnum,
        OtherItemCategory: 'OtherItemCategory' as CategoryEnum
    };
    export type ConditionEnum = 'USED' | 'NEW' | 'DEFECTIVE';
    export const ConditionEnum = {
        USED: 'USED' as ConditionEnum,
        NEW: 'NEW' as ConditionEnum,
        DEFECTIVE: 'DEFECTIVE' as ConditionEnum
    };
}