/**
 * GratisBrockiBackend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: @springdoc.version@
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';

export interface User { 
    id?: number;
    createdDate?: Date;
    lastModifiedDate?: Date;
    archivedDate?: Date;
    username?: string;
    email?: string;
    phoneNumber?: string;
    password?: string;
    role?: User.RoleEnum;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    credentialsNonExpired?: boolean;
    enabled?: boolean;
    items?: Array<Item>;
}
export namespace User {
    export type RoleEnum = 'ADMIN' | 'MODERATOR' | 'USER';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        MODERATOR: 'MODERATOR' as RoleEnum,
        USER: 'USER' as RoleEnum
    };
}